twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        images_directory: '/uploads/'
        images_product: '/images/products/'

when@test:
    twig:
        strict_variables: true


