twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        images_directory: '/uploads/'
        images_product: '/images/products/'
        site_name: 'angyz'
        phone: '07 85 45 82 30'
        address: '101, rue rambuteau'
        city : 'Paris'
        zipcode : '75001'
        country : 'France'
        email: 'ayeshsilva42@gmail.com'

when@test:
    twig:
        strict_variables: true


